#ifndef ITERATOR_H
#define ITERATOR_H

#define IteratorType(SELF_TYPE) CAT(SELF_TYPE, Iterator)
#define IterItem(SELF_TYPE)     CAT(IteratorType(SELF_TYPE), Item)

/* ********* iter_curr *********** */
#define ITER_CURR_FUNC_NAME(SELF_TYPE)      CAT(IteratorType(SELF_TYPE), _curr)
#define ITER_CURR_FUNC_SIGNATURE(SELF_TYPE) IterItem(SELF_TYPE) ITER_CURR_FUNC_NAME(SELF_TYPE)(SELF_TYPE* const self)
#define ITER_CURR_FUNC_IMPL(SELF_TYPE)\
    ITER_CURR_FUNC_SIGNATURE(SELF_TYPE)

#define iter_curr(SELF_TYPE, SELF)          ITER_CURR_FUNC_NAME(SELF_TYPE)(SELF)

/* ********* iter_begin *********** */
#define ITER_BEGIN_FUNC_NAME(SELF_TYPE)       CAT(IteratorType(SELF_TYPE), _begin)
#define ITER_BEGIN_FUNC_SIGNATURE(SELF_TYPE)  IterItem(SELF_TYPE) ITER_BEGIN_FUNC_NAME(SELF_TYPE)(SELF_TYPE* const self)
#define ITER_BEGIN_FUNC_IMPL(SELF_TYPE)\
    ITER_BEGIN_FUNC_SIGNATURE(SELF_TYPE)

#define iter_begin(SELF_TYPE, SELF)           ITER_BEGIN_FUNC_NAME(SELF_TYPE)(SELF)

/* ********* iter_end *********** */
#define ITER_END_FUNC_NAME(SELF_TYPE)       CAT(IteratorType(SELF_TYPE), _end)
#define ITER_END_FUNC_SIGNATURE(SELF_TYPE)  IterItem(SELF_TYPE) ITER_END_FUNC_NAME(SELF_TYPE)(SELF_TYPE* const self)
#define ITER_END_FUNC_IMPL(SELF_TYPE)\
    ITER_END_FUNC_SIGNATURE(SELF_TYPE)

#define iter_end(SELF_TYPE, SELF)           ITER_END_FUNC_NAME(SELF_TYPE)(SELF)

/* ********* iter_prev *********** */
#define ITER_PREV_FUNC_NAME(SELF_TYPE)       CAT(IteratorType(SELF_TYPE), _prev)
#define ITER_PREV_FUNC_SIGNATURE(SELF_TYPE)  IterItem(SELF_TYPE) ITER_PREV_FUNC_NAME(SELF_TYPE)(SELF_TYPE* const self)
#define ITER_PREV_FUNC_IMPL(SELF_TYPE)\
    ITER_PREV_FUNC_SIGNATURE(SELF_TYPE)

#define iter_prev(SELF_TYPE, SELF)           ITER_PREV_FUNC_NAME(SELF_TYPE)(SELF)


#define ITER_DEFS(SELF_TYPE, ITEM_TYPE)\
    typedef ITEM_TYPE* IterItem(SELF_TYPE);\
    ITER_CURR_FUNC_SIGNATURE(SELF_TYPE);\
    ITER_BEGIN_FUNC_SIGNATURE(SELF_TYPE);\
    ITER_END_FUNC_SIGNATURE(SELF_TYPE);\
    ITER_PREV_FUNC_SIGNATURE(SELF_TYPE);\

#define ITER_IMPL(SELF_TYPE, CURR_IMPL, BEGIN_IMPL, END_IMPL, PREV_IMPL)\
    ITER_CURR_FUNC_IMPL(SELF_TYPE)  CURR_IMPL\
    ITER_BEGIN_FUNC_IMPL(SELF_TYPE) BEGIN_IMPL\
    ITER_END_FUNC_IMPL(SELF_TYPE)   END_IMPL\
    ITER_PREV_FUNC_IMPL(SELF_TYPE)  PREV_IMPL\


#define FOREACH(SELF_TYPE, EL, IT) \
    for (IterItem(SELF_TYPE) EL = iter_begin(SELF_TYPE, IT); EL != NULL; EL = iter_next(SELF_TYPE, IT))


#endif