#ifndef LOKI_ERROR_H
#define LOKI_ERROR_H

#include "utils/result.h"

typedef enum {
    SUCCESS = OK_CODE,

    ERR_TERM_READ_ATTR,
    ERR_TERM_WRITE_ATTR,
    ERR_TERM_GET_CURSOR_POS,
    ERR_TERM_ESC_SEQ,

    ERR_CMD_NOT_KNOWN,
    ERR_CMD_NEW,

    ERR_CORE_INSERT_ROW,
    ERR_CORE_INSERT_NEWLINE,
    ERR_CORE_DELETE_CHAR_INVALID_EP,
    ERR_CORE_APPEND_NEXT_ROW,
    ERR_CORE_DELETE_NO_ROWS,
} ErrorCode;


#endif